name: Testing on macOS
on: [push, pull_request]
jobs:
  macOS-Catalina-10-15:
    runs-on: macos-10.15
    steps:
      - name: Set up environment
        shell: bash
        run: brew install coreutils
      - uses: actions/checkout@v2
      - name: Run script
        shell: bash
        run: ./scripts/test.sh
