name: Testing
on: [push, pull_request]
jobs:
  Testing-on-Windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run test script
        run: ./scripts/test.sh
        shell: bash
  Testing-on-MacOS:
    runs-on: macos-latest
    steps:
#       - uses: maxim-lobanov/setup-xcode@v1
#         with:
#           xcode-version: '12.0.1'
      - uses: actions/checkout@v1
      - name: Run test script
        run: ./scripts/test.sh -d
        shell: bash
  Testing-on-Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run test script
        run: ./scripts/test.sh
        shell: bash
