name: Testing Ubuntu
on: [push, pull_request]
jobs:
  Ubuntu-20-04:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run script
        shell: bash
        run: ./scripts/test.sh
